const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
gsap.registerPlugin(ScrollTrigger);
const lenis=reduce?null:new Lenis({duration:1.05,smoothWheel:true,anchors:true});
if(lenis){lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0);}
// Opening header details recede while the two navigation controls remain available.
if(!reduce){
  const headerMotion=gsap.timeline({scrollTrigger:{start:0,end:()=>Math.min(360,innerHeight*.55),scrub:.25,invalidateOnRefresh:true}});
  headerMotion.to('.site-header',{'--header-detail-opacity':0,duration:1,ease:'none'},0)
    .to('.header-motto',{opacity:0,duration:1,ease:'none'},0)
    .to('.site-header > .monogram',{x:()=>-innerWidth*(innerWidth<=700?.025:.04),duration:1,ease:'none'},0)
    .to('.site-header > .menu-toggle',{x:()=>innerWidth*(innerWidth<=700?.025:.04),duration:1,ease:'none'},0);
}
let cadDispose=null,cadGeneration=0;
function clearCAD(){cadGeneration++;cadDispose?.();cadDispose=null;}
let activeProject=0, currentDialog=null, restoreFocus=null, closing=false;
const navButtons=()=>sections.map((s,i)=>`<button data-panel="${s.id}"><span class="nav-number">0${i+1}</span><span>${s.title}</span><span class="nav-arrow">↗</span></button>`).join('');
$('.resume-grid').innerHTML=navButtons();
document.body.insertAdjacentHTML('beforeend',`<dialog id="navigation" class="overlay nav-overlay" aria-labelledby="nav-title"><div class="overlay-top"><a class="monogram" href="#" data-home>LT</a><span class="eyebrow" id="nav-title">EXPLORE THE PORTFOLIO</span><button class="close-dialog" aria-label="Close menu">CLOSE <span>×</span></button></div><nav class="overlay-nav" aria-label="Portfolio sections">${navButtons()}</nav><div class="overlay-bottom"><span>LUCAS TAN PENG LIANG</span><a href="https://www.linkedin.com/in/lucastan03" target="_blank" rel="noopener noreferrer">LINKEDIN ↗</a></div></dialog><dialog id="information" class="overlay info-overlay" aria-labelledby="panel-title"><div class="overlay-top"><button class="back-menu">← ALL SECTIONS</button><span class="eyebrow">LUCAS TAN / RESUME</span><button class="close-dialog" aria-label="Close information panel">CLOSE <span>×</span></button></div><div class="panel-scroll" data-lenis-prevent><div class="panel-heading"><p class="eyebrow" id="panel-number"></p><h2 id="panel-title"></h2></div><div class="panel-content"></div><button class="panel-end close-dialog">BACK TO PORTFOLIO ↑</button></div></dialog><dialog id="welcome" class="welcome" aria-labelledby="welcome-title"><button class="welcome-close" aria-label="Dismiss introduction">×</button><p class="eyebrow">PERSONAL PORTFOLIO</p><h2 id="welcome-title">Lucas Tan<br>Peng Liang</h2><p class="welcome-discipline">Mechanical Engineering</p><p>An interactive engineering portfolio using motion and visual storytelling to present my projects, experience and technical capabilities.</p><button class="welcome-enter">EXPLORE PORTFOLIO <span>↗</span></button></dialog>`);
function showDialog(d,keepFocus=false){if(closing)return;if(currentDialog?.id==='information'&&d.id!=='information')clearCAD();if(!keepFocus)restoreFocus=document.activeElement;if(currentDialog)currentDialog.close();currentDialog=d;gsap.killTweensOf(d);d.style.pointerEvents='none';d.showModal();lenis?.stop();document.documentElement.classList.add('modal-open');$('.menu-toggle').setAttribute('aria-expanded',d.id==='navigation'?'true':'false');gsap.fromTo(d,{clipPath:'inset(100% 0 0 0)'},{clipPath:'inset(0% 0 0 0)',duration:reduce?0:.7,ease:'power3.inOut',onComplete:()=>{d.style.pointerEvents='auto';}});if(d.id==='navigation')gsap.fromTo(d.querySelectorAll('nav button'),{y:40,opacity:0},{y:0,opacity:1,stagger:.055,duration:reduce?0:.65,delay:reduce?0:.25,ease:'power3.out'});}
function closeDialog(){if(!currentDialog||closing)return;closing=true;const d=currentDialog;gsap.to(d,{clipPath:'inset(0 0 100% 0)',duration:reduce?0:.45,ease:'power3.inOut',onComplete:()=>{if(d.id==='information')clearCAD();d.close();currentDialog=null;closing=false;document.documentElement.classList.remove('modal-open');lenis?.start();$('.menu-toggle').setAttribute('aria-expanded','false');restoreFocus?.focus({preventScroll:true});}});}
function showPanel(id,projectIndex=null){const i=sections.findIndex(s=>s.id===id),s=sections[i];if(!s)return;clearCAD();$('#panel-title').textContent=s.title;$('#panel-number').textContent=`0${i+1} / 06`;$('.panel-content').innerHTML=s.entries.map((e,j)=>`<article class="resume-entry" id="entry-${j}"><div class="entry-meta"><span>${e.date||''}</span>${e.role?`<span>${e.role}</span>`:''}</div><div class="entry-body">${id==='projects'&&e.image==='arduino.jpg'?`<div class="cad-viewer" aria-label="Arduino Bot interactive CAD viewer"></div>`:e.image?`<img src="assets/${e.image}" alt="${e.title}" class="entry-image">`:''}<h3>${e.title}</h3>${e.subtitle?`<p class="entry-subtitle">${e.subtitle}</p>`:''}${e.points.length?`<ul>${e.points.map(p=>`<li>${p}</li>`).join('')}</ul>`:''}</div></article>`).join('');showDialog($('#information'),!!currentDialog);$('.panel-scroll').scrollTop=0;const cadHost=$('.cad-viewer'),cadTicket=cadGeneration;if(cadHost)import('./cad-viewer.js').then(m=>{if(cadHost.isConnected&&cadTicket===cadGeneration)cadDispose=m.mount(cadHost);}).catch(()=>{if(cadHost.isConnected)cadHost.textContent='The 3D viewer could not load. Please reopen this project to try again.';});if(projectIndex!==null)requestAnimationFrame(()=>{const e=$(`#entry-${projectIndex}`);$('.panel-scroll').scrollTop=e.offsetTop-$('.panel-scroll').offsetTop-20;});}
$('.menu-toggle').addEventListener('click',()=>showDialog($('#navigation')));
document.addEventListener('click',e=>{const b=e.target.closest('[data-panel]');if(b)showPanel(b.dataset.panel,b.classList.contains('explore-current')?activeProject:null);if(e.target.closest('.close-dialog'))closeDialog();if(e.target.closest('.back-menu'))showDialog($('#navigation'),true);if(e.target.closest('[data-home]')){e.preventDefault();closeDialog();setTimeout(()=>lenis?lenis.scrollTo(0):window.scrollTo({top:0,behavior:'smooth'}),reduce?0:460);}});
$$('dialog').forEach(d=>d.addEventListener('cancel',e=>{e.preventDefault();d.id==='welcome'?dismissWelcome():closeDialog();}));
function dismissWelcome(){try{sessionStorage.setItem('lucas-portfolio-visited','1');}catch{}closeDialog();}
$('.welcome-close').onclick=dismissWelcome;$('.welcome-enter').onclick=dismissWelcome;
let visited=false;try{visited=sessionStorage.getItem('lucas-portfolio-visited')==='1';}catch{}
if(!visited)showDialog($('#welcome'));
const stage=$('.stage');$('.project-visual').remove();$('.project-copy').remove();
stage.insertAdjacentHTML('beforeend',projects.map((p,i)=>`<article class="project-slide slide-${i}" data-index="${i}" aria-hidden="${i!==0}"><div class="project-visual visual-${i}"><img src="assets/${p.image}" alt="${p.name}"></div><div class="project-copy"><p class="eyebrow">${p.category} / ${p.year}</p><${i===0?'h1':'h2'}>${p.name==='Supply Chain Challenge'?'Supply Chain<br>Challenge':p.name}</${i===0?'h1':'h2'}><p class="project-description">${p.summary}</p></div></article>`).join(''));
$('.line-control').classList.add('explore-current');
$('.stage-bottom').insertAdjacentHTML('beforeend',`<div class="project-markers" aria-label="Choose a project">${projects.map((p,i)=>`<button aria-label="Show ${p.name}" data-project="${i}" ${i===0?'aria-current="true"':''}><span>0${i+1}</span></button>`).join('')}</div>`);
function setProject(i){activeProject=i;$('.project-counter').textContent=`0${i+1} — 05`;$$('.project-slide').forEach((e,j)=>e.setAttribute('aria-hidden',j!==i));$$('[data-project]').forEach((e,j)=>j===i?e.setAttribute('aria-current','true'):e.removeAttribute('aria-current'));}
let projectTimeline;
if(!reduce){
gsap.set('.project-slide',{autoAlpha:0});gsap.set('.slide-0',{autoAlpha:1});
projectTimeline=gsap.timeline({scrollTrigger:{trigger:'.showcase',start:'top top',end:()=>'+='+window.innerHeight*5.4,pin:'.stage',scrub:.55,invalidateOnRefresh:true,onUpdate:self=>{const time=self.progress*projectTimeline.duration();setProject(Math.min(4,Math.max(0,Math.floor((time+.4)/1.65))));}}});
projectTimeline.to({}, {duration:.7});
const entrances=[{}, {xPercent:60,yPercent:35,rotation:12,scale:.7}, {xPercent:0,yPercent:90,rotation:-7,scale:.85}, {xPercent:-80,yPercent:5,rotation:-14,scale:1.1}, {xPercent:30,yPercent:50,rotation:8,scale:.6}];
const exits=[{xPercent:-25,yPercent:-70,rotation:-12,scale:.7},{xPercent:-70,yPercent:5,rotation:-15,scale:.85},{xPercent:20,yPercent:-90,rotation:4,scale:.75},{xPercent:70,yPercent:0,rotation:14,scale:.8}];
for(let i=1;i<5;i++){const at=.7+(i-1)*1.65;projectTimeline.to(`.slide-${i-1} .project-visual`,{...exits[i-1],opacity:0,duration:1.05,ease:'power2.inOut'},at).to(`.slide-${i-1} .project-copy`,{y:-65,opacity:0,duration:.55},at).set(`.slide-${i}`,{autoAlpha:1},at+.15).fromTo(`.slide-${i} .project-visual`,{...entrances[i],opacity:0,clipPath:'inset(12% 12% 12% 12% round 40%)'},{xPercent:0,yPercent:0,rotation:i%2?4:-3,scale:1,opacity:1,clipPath:'inset(0% 0% 0% 0% round 2%)',duration:1.2,ease:'power2.inOut'},at+.15).fromTo(`.slide-${i} .project-copy`,{y:85,opacity:0},{y:0,opacity:1,duration:.8,ease:'power2.out'},at+.48);}
projectTimeline.to({}, {duration:.75});
const identity=gsap.timeline({scrollTrigger:{trigger:'.identity',pin:'.identity-stage',start:'top top',end:()=>'+='+window.innerHeight*2.2,scrub:.65,invalidateOnRefresh:true}});
identity.to({}, {duration:.25}).to('.english-name span:first-child',{xPercent:-95,yPercent:-20,rotation:-8,opacity:0,duration:1.5,ease:'power2.inOut'},.25).to('.english-name span:last-child',{xPercent:110,yPercent:25,rotation:9,opacity:0,duration:1.5,ease:'power2.inOut'},.25).fromTo('.chinese-name span',{y:140,rotationY:65,scale:.7,opacity:0,filter:'blur(16px)'},{y:0,rotationY:0,scale:1,opacity:1,filter:'blur(0px)',duration:1.35,stagger:.16,ease:'power2.out'},.85).to('.identity-stage',{backgroundColor:'#a3f2ef',color:'#174e51',duration:.8},1.7).to({}, {duration:.5});
const about=gsap.timeline({scrollTrigger:{trigger:'.about',pin:'.about-stage',start:'top top',end:()=>'+='+window.innerHeight*2.5,scrub:.5,onUpdate:self=>{const i=Math.min(2,Math.floor(self.progress*3));$$('.word').forEach((w,j)=>w.classList.toggle('active',j===i));$('.about-index').textContent=`0${i+1} / 03`;}}});
gsap.set('.about-text:not(:first-child)',{autoAlpha:0,y:65});
about.to({}, {duration:.6}).to('.about-text:nth-child(1)',{y:-70,autoAlpha:0,duration:.5}).to('.about-text:nth-child(2)',{y:0,autoAlpha:1,duration:.6},'<.2').to({}, {duration:.55}).to('.about-text:nth-child(2)',{y:-70,autoAlpha:0,duration:.5}).to('.about-text:nth-child(3)',{y:0,autoAlpha:1,duration:.6},'<.2').to({}, {duration:.8});
gsap.from('.resume-grid button',{y:40,opacity:0,stagger:.08,duration:.8,scrollTrigger:{trigger:'.resume-grid',start:'top 90%'}});
}else{document.body.classList.add('reduced-motion');$$('.project-slide').forEach(e=>e.removeAttribute('aria-hidden'));}
$$('[data-project]').forEach(b=>b.addEventListener('click',()=>{const i=Number(b.dataset.project);if(projectTimeline){const st=projectTimeline.scrollTrigger;const time=i===0?0:.7+(i-1)*1.65+1.4;const target=st.start+(time/projectTimeline.duration())*(st.end-st.start);lenis?lenis.scrollTo(target,{duration:1.2}):window.scrollTo(0,target);}else{$(`.slide-${i}`).scrollIntoView();setProject(i);}}));
window.addEventListener('load',()=>ScrollTrigger.refresh());document.fonts.ready.then(()=>ScrollTrigger.refresh());


